EMBEDDING_MODEL_NAME = "models/gemini-embedding-001"
GENERATIVE_MODEL_NAME = "models/gemini-2.5-flash"

DOCUMENT_CHUNK_SIZE = 500
DOCUMENT_CHUNK_OVERLAP = 50
RETRIEVAL_TOP_K_RESULTS = 2
TEMPERATURE = 0.0

DEFAULT_KNOWLEDGE_SOURCE = "my_story.txt"
LANGUAGE_URDU = "Urdu"
PAGE_TITLE = "Lahore Archive"
